name: CI

on:
  push:
    branches: [mine]
  pull_request:
    branches: [mine]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      # GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo 'Hello, world!'

      - name: Run a multi-line script
        run: |
          echo 'Add other actions to build,'
          echo 'test, and deploy your project'

  report-url:
    runs-on: self-hosted
    steps:
      - run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
