name: Simple Go Build

# on:
  # push:
  #   branches:
  #     - mine

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup Go version
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.2'
    - run: go run ./helloworld.go
